= AddressBook Level 4 - Developer Guide

== Value Proposition

Current:
. Tutors use reminder applications to keep track of lessons
. Tutors use physical diaries or notepads to keep track of current lesson progress
Value:
. Tutors have a platform where they can keep track of all their student’s lessons
  as well as the progress and syllabus which they have or intend to cover

== User Stories
. For private tutors to manage individual students’ schedule. As a tutor, I want
  to be able to know where my students live, what time their tuition is,
  their individual syllabus progress, and my weekly schedule.

== Use Cases
. Actor: Tutor
  MSS: Delete/Edit student sessions
  Precondition:

  -> Step 1:
  Actor: Tutor
  Action: Type command ‘Delete/Edit <STUDENT NAME>’ on the CLI bar
  -> Step 2:
  Actor: System
  Action: System attempts to locate the data of specified student
          inside the database and deletes/edit if present
  -> Step 3a.1:
  Actor: System
  Action: System finds the specified student.
  -> Step 3a.2:
  Actor: System
  Action: System deletes/edits student details
  -> Step 3b.1:
  Actor: System
  Action: System cannot find the specified student inside the database
  -> Step 3b.2:
  Actor: System
  Action: System asks user to re-enter command, Go back to Step 1

. MSS: View students details (progress, level, syllabus, location, time of tuition)
  Precondition: Tutor is logged in

  ->Step 1:
  Actor: Tutor
  Action: Type command ‘view <STUDENT NAME>’ on the CLI bar.
  ->Step 2:
  Actor: System
  Action: System locates the data of specified student inside the database
  ->Step 3a.1
  Actor: System
  Action: System can find the specified student.
  -> Step 3a.2:
  Actor: System
  Action: System displays the detail of students onto the screen.
  -> Step 3b.1:
  Actor: System
  Action: System cannot find the specified student inside the database
  -> Step 3b.2:
  Actor: System
  Action: System asks’ for next user query

. MSS: Tracking students progress
  Precondition: Tutor is logged in
  Steps:
    -View Student Details
    -Edit Syllabus Progress

  -> Step 1:
  Actor: Tutor
  Action: Type command ‘progress <STUDENT NAME>’ on the CLI bar.
  -> Step 2:
  Actor: System
  Action: System locates the data of specified student inside the database
  -> Step 3a.1:
  Actor: System
  Action: System can find the specified student.
  -> Step 3a.2:
  Actor: System
  Action: System compares student progress to the syllabus
  being used by the students
  -> Step 3a.3:
  Actor: System
  Action: System displays students’ progress in terms of percentage
  -> Step 3b.1:
  Actor: System
  Action: System cannot find the specified student inside the database
  -> Step 3b.2:
  Actor: System
  Action: System asks’ for next user query


== Non-Functional Requirements

. Display a list of upcoming sessions with students
. Must be accurate
. Must be fast in displaying results
. Can view own timetable
. Integrate google map to reach students’ location

== Glossary
. Syllabus: the subjects in a course of study or teaching.
