= TutorHelper - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
:experimental:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-W13-4/main/tree/master

== Value Proposition

Current: +

* `Tutors use reminder applications to keep track of lessons`
* `Tutors use physical diaries or notepads to keep track of current lesson progress`

Value: 

* `Tutors have a platform where they can keep track of all their student’s details, +
their progress and the syllabus they intend to cover.`

== User Stories
. For private tutors to manage individual students’ schedule. 
  As a tutor, I want to be able to know where my students live, what time their tuition is, their individual syllabus progress, and my weekly schedule.

== Use Cases
 
  1. MSS: Add Student

  Step 1:
  Actor: Tutor
  Action: Type command 'add' or 'a' followed by Student details on the CLI bar
  Step 2a:
  Input is valid and student details added into the database
  Step 2b:
  Input is invalid and error message displayed
  
  2. MSS: Edit Student

  Step 1:
  Actor: Tutor
  Action: Type command 'edit' or 'e' followed by the index and the fields to edit
  Step 2a:
  Input is valid and student details successfully edited.
  New student details displayed
  Step 2b:
  Input is invalid and error message displayed

  3. MSS: Delete Student
  
  Step 1:
  Actor: Tutor
  Action: Type command 'delete' or 'd' followed by the index to delete
  Step 2:
  Student corresponding to the index is removed from TutorHelper


== Non-Functional Requirements

. Display a list of upcoming sessions with students
. Must be fast in displaying results
. Can view own timetable

== Glossary
. Syllabus: the subjects in a course of study or teaching.
