= TutorHelper - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
:experimental:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-W13-4/main/tree/master

== Value Proposition

Current: +

* `Tutors use reminder applications to keep track of lessons`
* `Tutors use physical diaries or notepads to keep track of current lesson progress`

Value:

* `Tutors have a platform where they can keep track of all their students' details, their progress and the syllabus they intend to cover.`

== User Stories

. As a busy tutor, I want to be able to manage my students' schedules individually, so that I can plan my time properly.
. As a tutor, I want to be able to find out where my students live and what time I should be there for tuition.
. As a tutor, I want to know my students' individual progress so that I know what topics I need to cover for the next tuition session.
. As a tutor, I want to keep track of my students' payments.

== Use Cases

  1. Add Student

  System: TutorHelper
  Actor: Tutor
  MSS:
    1. Tutor inputs to add a student and his/her details.
    2. System adds student details into the database.
    Use case ends.
  Extensions:
    2a. Index is out of bounds
      2a1. System displays error message.

  2. Edit Student

  System: TutorHelper
  Actor: Tutor
  MSS:
    1. Tutor inputs to edit a student's details.
    2. System edits student details into the database.
    Use case ends.
  Extensions:
    2a. Index is out of bounds
      2a1. System displays error message.

  3. Delete Student

  System: TutorHelper
  Actor: Tutor
  MSS:
    1. Tutor inputs student's index to delete.
    2. System deletes student details from the database.
    Use case ends.
  Extensions:
    2a. Index is out of bounds
      2a1. System displays error message.

  4. List Students

  System: TutorHelper
  Actor: Tutor
  MSS:
    1. Tutor requests to list students.
    2. System displays current list of students.
    Use case ends.

  5. Group Students

  System: TutorHelper
  Actor: Tutor
  Precondition: Current list of students is not empty.
  MSS:
    1. Tutor requests to group students by day or timing.
    2. System filters the current list of students based on the timing entered.
    3. System sorts the filtered list of students in order of timing.
    4. System displays filtered and sorted list to Tutor.
    Use case ends.
  Extensions:
    2a. Input is invalid
      2a1. System displays examples of valid input to Tutor.
    2b. Tutor does not input a day or timing
      2b1. System retrieves current date.
      2b2. System filters out students with tuition before current date.
      2b3. Resume from step 3.

  6. Record students' payments

    System: TutorHelper
    Actor: Tutor
    Precondition: student index entered must be valid.
    MSS:
      1. Tutor request to add in payment for a student.
      2. System searches for that student according to index entered.
      3. System adds Payment amount, month and year to student's record.
      4. System displays payment record in browser panel.
      5. System displays successful recording of payment under command box.
     Extensions:
      2a. Tutor does not enter all the required entries correctly
        2a1. System displays error message
        2a2. System gives tutor an example of a correct entry.
      2b. Tutor does not enter a valid student index
        2b1. System displays error message telling tutor that index is invalid

  7. Displays tutor's earnings for that month and year
  
     System: TutorHelper
     Actor: Tutor
     Precondition: Tutor has recorded payment from students before.
     MSS:
        1. Tutor request for earnings for a specific month and year.
        2. System searches for all the payment records made from all the students for that particular month and year.
        3. System adds up all the payment.
        4. System displays total earnings under the command box.
     Extensions:
        2a. System does not find any payment recorded for that month and year.
            2a1. System displays $0 as result.

== Non-Functional Requirements

. The system should respond in two seconds.
. The system should be understandable to a novice in working with computers.

== Glossary
. Syllabus: the topics of a particular subject in a course of study or teaching.
